apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysqlaccount
  name: mysqlaccount
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlaccount
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlaccount
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: accounts
        - name: MYSQL_PASSWORD
          value: dummy
        - name: MYSQL_ROOT_PASSWORD
          value: dummy
        - name: MYSQL_USER
          value: sudheesh
        image: mysql:5
        args: "--ignore-db-dir=lost+found" #CHANGE
        name: mysqlaccount
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-accountdatabase-data-volume
      restartPolicy: Always
      volumes:
      - name: mysql-accountdatabase-data-volume
        persistentVolumeClaim:
          claimName: mysql-accountdatabase-data-volume
