apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqlaccount
  name: mysqlaccount
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysqlaccount
