apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqlportfolios
  name: mysqlportfolios
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "3307"
    port: 3307
    targetPort: 3306
  selector:
    app: mysqlportfolios
