apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqlquotes
  name: mysqlquotes
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysqlquotes
