apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-quotesdatabase-data-volume
  name: mysql-quotesdatabase-data-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
